### Registration
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "mark@gmail.com",
    "password": "mark1234"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "mark@gmail.com",
    "password": "mark1234"
}

### Get User Own Profile
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDM1ZTRhYWRkM2Y5MTU3YzhhZmMyMzMiLCJlbWFpbCI6Im1hcmtAZ21haWwuY29tIiwicm9sZXMiOlsidXNlciJdLCJpYXQiOjE2MTQxNDQ2ODMsImV4cCI6MTYxNDc0OTQ4M30.UR5c4Ih1xoRfxnTqLdQ5nRf1sSVh_EVyNK4mpSuD_nc